"""Render a Captify schematic graph as EDML for Altair EEvision.

Written to the official "EDML — The Electrical Design Modeling Language"
specification (Altair, version 2025), compiled by EEvision's ``edml2edb``:

* every statement ends with ``;``; objects must be DECLARED before use, so
  all ``Wire`` statements come first, then components with their
  ``Connector`` / ``Cavity`` / ``Join`` blocks,
* identifiers are ``[0-9A-Za-z_]+``; printed names ride in the ``Name``
  property; part numbers and provenance ride as quoted attributes,
* wires classify via ``Type = power|ground|logical`` (MIL-W-5088 ``…N``
  wire ids are grounds), and components display EEvision's built-in
  DIN 40719-2 symbols via ``Imagedsp`` (``R`` resistor, ``K`` relay, …),
* cavities ARE the recovered pin designators, so EEvision shows real pin
  identities at every connection point.

Like the other serializers this is pure and deterministic over the
``captify.schematic.v1`` graph.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from docling_serve.schematic.eevision import (
    cavity_ids_for,
    din_symbol,
    net_connection_plan,
    net_label,
    safe_id,
    wire_type,
)


def _q(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def graph_to_edml(graph: dict[str, Any], *, source_name: str) -> str:
    """Serialize a ``captify.schematic.v1`` graph to a spec-conformant EDML string."""
    components = [c for c in graph.get("components") or [] if isinstance(c, dict)]
    nets = [n for n in graph.get("nets") or [] if isinstance(n, dict)]

    lines: list[str] = [
        "// EDML generated by captify-docling-serve schematic extractor",
        f"// Source: {source_name}",
        "",
    ]

    # Root attributes (shown on EEvision's file-select page via Index).
    title = (graph.get("pages") or [{}])[0].get("titleBlock") or {}
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%SZ")
    lines.append(
        "Attributes Index = " + _q("Source\tTitle\tGenerated") + ","
    )
    lines.append(f"    {_q('Source')} = {_q(source_name)},")
    lines.append(f"    {_q('Title')} = {_q(title.get('title') or source_name)},")
    lines.append(f"    {_q('Generated')} = {_q(generated)};")
    lines.append("")

    # 1. Wires — declared before any component can Join them (spec §3.1).
    wire_ref_by_net: dict[str, str] = {}
    lines.append("// Wires (one per traced net)")
    for index, net in enumerate(nets, start=1):
        ref = safe_id(net.get("wireId") or net.get("id"), f"W{index:03d}")
        wire_ref_by_net[str(net.get("id") or index)] = ref
        properties = [f"Name = {_q(net_label(net, index))}"]
        classified = wire_type(net)
        if classified:
            properties.append(f"Type = {classified}")
        if net.get("gauge"):
            properties.append(f'{_q("Gauge")} = {_q(net["gauge"])}')
        if net.get("wireIdSource") == "assigned":
            properties.append(f'{_q("Wire Id Source")} = {_q("assigned")}')
        lines.append(f"Wire {ref} | " + ", ".join(properties) + ";")
    lines.append("")

    # 2. Components: one connector, pin-designator cavities, Joins to wires,
    #    Arcs for component-internal connections (duplicate net memberships).
    raw_ids = {str(c.get("id")) for c in components}
    cavities = {raw_id: cavity_ids_for(raw_id, nets) for raw_id in raw_ids}
    plan = net_connection_plan(nets, raw_ids, cavities)
    joins_by_component: dict[str, list[str]] = {}
    arcs_by_component: dict[str, list[tuple[str, str]]] = {}
    for net, entry in zip(nets, plan):
        net_ref = wire_ref_by_net.get(str(net.get("id")))
        if not net_ref:
            continue
        for comp_id, cavity in entry["endpoints"]:
            joins_by_component.setdefault(comp_id, []).append(f"A.{cavity} -> {net_ref}")
        for comp_id, first_cavity, extra_cavity in entry["arcs"]:
            arcs_by_component.setdefault(comp_id, []).append((first_cavity, extra_cavity))

    lines.append("// Components")
    seen_ids: set[str] = set()
    for order, component in enumerate(components, start=1):
        comp_id = safe_id(component.get("id"), f"C{order:04d}")
        if comp_id in seen_ids:
            comp_id = f"{comp_id}_{order}"
        seen_ids.add(comp_id)
        raw_id = str(component.get("id"))
        lines.extend(
            _component_block(
                comp_id,
                component,
                cavities.get(raw_id, {}),
                joins_by_component.get(raw_id, []),
                arcs_by_component.get(raw_id, []),
            )
        )
        lines.append("")

    # 3. Signal modules: one per PRINTED net name, grouping its wire — the
    #    EEvision-side handle for "show me everything carrying CATHODE_0".
    signal_lines = _signal_modules(nets, wire_ref_by_net)
    if signal_lines:
        lines.append("// Signal modules (printed net names)")
        lines.extend(signal_lines)
        lines.append("")

    return "\n".join(lines) + "\n"


def _signal_modules(
    nets: list[dict[str, Any]], wire_ref_by_net: dict[str, str]
) -> list[str]:
    """``Signal`` statements for nets whose name was printed on the drawing.

    Assigned wire ids (``wireIdSource == "assigned"`` with no printed name)
    carry no signal meaning, so they get no module. Nets sharing one printed
    name collapse into one module.
    """
    wires_by_signal: dict[str, list[str]] = {}
    for net in nets:
        name = str(net.get("name") or "").strip()
        if not name or name == str(net.get("wireId") or ""):
            continue
        ref = wire_ref_by_net.get(str(net.get("id")))
        if ref:
            wires_by_signal.setdefault(name, []).append(ref)

    lines: list[str] = []
    used: set[str] = set()
    for order, (name, refs) in enumerate(sorted(wires_by_signal.items()), start=1):
        sig_id = safe_id(name, f"SIG{order:03d}")
        if sig_id in used:
            sig_id = f"{sig_id}_{order}"
        used.add(sig_id)
        lines.append(f"Signal {sig_id} (" + ", ".join(refs) + f") | Name = {_q(name)};")
    return lines


def _component_block(
    comp_id: str,
    component: dict[str, Any],
    cavity_by_membership: dict[int, str],
    joins: list[str],
    arcs: list[tuple[str, str]],
) -> list[str]:
    """The EDML statements for one component (declaration, cavities, joins, arcs)."""
    properties = [f"Name = {_q(component.get('refDes') or comp_id)}"]
    symbol = din_symbol(component)
    if symbol:
        properties.append(f"Imagedsp = {_q(f'{symbol},40,40')}")
    for field, label in (
        ("partNumber", "Part No"),
        ("type", "Component Type"),
        ("value", "Value"),
        ("location", "Location"),
    ):
        if component.get(field):
            properties.append(f"{_q(label)} = {_q(component[field])}")
    lines = [f"Component {comp_id} | " + ", ".join(properties) + ";"]

    # Cavities in membership order; the cavity id IS the pin designator.
    cavity_ids = [cavity_by_membership[k] for k in sorted(cavity_by_membership)]
    if cavity_ids:
        lines.append("Connector A | Type = invisible;")
        lines.append("Cavity " + ", ".join(cavity_ids) + ";")
    if joins:
        lines.append("Join " + ", ".join(joins) + ";")
    # Component-internal connections (spec §3.6.1 "Arcs"): extraction saw the
    # same net touch this component more than once — model the extra contact
    # as an internal electrical connection, not a wire looping back.
    for arc_no, (first_cavity, extra_cavity) in enumerate(arcs, start=1):
        lines.append(f"Arc {comp_id}_arc{arc_no} (A.{first_cavity}, A.{extra_cavity});")
    return lines
