"""Render a Captify schematic graph as a generic SPICE netlist (.cir).

SPICE is the one simulation-capable format shared across the toolchains we
target: KiCad imports and simulates it natively (bundled ngspice), and the
Altair EDA family EEvision belongs to reads it through SpiceVision /
StarVision PRO (generic SPICE plus the commercial dialects). Emitting plain,
dialect-free SPICE keeps every door open.

Mapping from ``captify.schematic.v1``:

* nets → SPICE nodes (sanitized printed names — A8B22 stays A8B22),
* passives with a recognizable type → native primitives (R/C/L) so a
  simulator can elaborate them directly,
* everything else (valves, relays, ICs, switches) → ``X`` subcircuit
  instances against generated ``.subckt`` stubs that carry the printed part
  number and pin count — simulation-ready scaffolding a user fills with real
  models, and exactly the shape SpiceVision renders as schematic symbols.

Like the other serializers, this is pure and deterministic; the test suite
parses the output with ngspice in batch mode when it is installed.
"""

from __future__ import annotations

import re
from typing import Any

#: SPICE element prefixes by (lower-cased substring of) component type.
_PRIMITIVES = (
    ("resistor", "R"),
    ("capacitor", "C"),
    ("inductor", "L"),
)

_NODE_SANITIZE_RE = re.compile(r"[^A-Za-z0-9_]")


def graph_to_spice(graph: dict[str, Any], *, source_name: str) -> str:
    """Serialize a ``captify.schematic.v1`` graph to a SPICE netlist string.

    Model resolution per component, in order: catalog/vendor model →
    inferred first-order physics (``spice_inference``) → connectivity stub.
    """
    from docling_serve.schematic.spice_inference import (
        InferredBody,
        infer_subckt_body,
        model_cards_for,
    )
    from docling_serve.schematic.spice_models import find_model

    components = [c for c in graph.get("components") or [] if isinstance(c, dict)]
    nets = [n for n in graph.get("nets") or [] if isinstance(n, dict)]
    tenant_id = _graph_tenant(graph)

    node_by_membership = _node_assignments(nets)

    lines: list[str] = [
        f"* {graph.get('titleBlock', {}).get('title') or source_name}".strip(),
        f"* Generated by captify-docling-serve schematic extractor from {source_name}",
        "* Generic SPICE netlist: vendor models bind from the model library;",
        "* INFERRED subcircuits carry first-order physics derived from the",
        "* component type; remaining stubs await vendor models.",
        "",
    ]

    subckts: dict[str, int] = {}  # stub subckt name -> pin count
    inferred: dict[str, tuple[int, InferredBody]] = {}  # subckt -> (pins, body)
    bound_models: dict[str, str] = {}  # model name -> model text
    primitive_wrappers: dict[str, tuple[int, str]] = {}  # subckt -> (pins, body)
    element_names: set[str] = set()
    for index, component in enumerate(components, start=1):
        comp_id = str(component.get("id") or f"C{index:04d}")
        ref = _sanitize(str(component.get("refDes") or comp_id))
        ctype = str(component.get("type") or "").lower()
        nodes = node_by_membership.get(comp_id) or []
        pins = [p for p in component.get("pins") or [] if isinstance(p, dict)]
        pin_count = max(len(nodes), len(pins), 2)

        # A catalog-supplied vendor model fixes the TRUE pin count; the
        # instance binds it directly and becomes genuinely simulatable.
        model = find_model(component.get("partNumber"), tenant_id=tenant_id)
        if model is not None and model.is_subckt:
            pin_count = model.pin_count

        nodes = (nodes + [f"NC_{ref}_{i}" for i in range(len(nodes), pin_count)])[
            :pin_count
        ]

        if model is not None and model.is_subckt:
            bound_models[model.name] = model.text
            name = _unique(f"X{ref}", element_names, "X")
            lines.append(f"{name} {' '.join(nodes)} {model.name}")
            continue

        # Vendor ``.model`` card (primitive device, not a subcircuit): wrap it
        # in a generated subckt instantiating the right SPICE element, when
        # the traced pin count matches the device's terminals.
        if model is not None:
            wrapper = _primitive_wrapper(model, pin_count)
            if wrapper is not None:
                wrapper_name, body = wrapper
                bound_models[model.name] = model.text
                primitive_wrappers[wrapper_name] = (pin_count, body)
                name = _unique(f"X{ref}", element_names, "X")
                lines.append(f"{name} {' '.join(nodes)} {wrapper_name}")
                continue

        prefix = next(
            (p for token, p in _PRIMITIVES if token in ctype), None
        )
        if prefix and pin_count == 2:
            name = _unique(f"{prefix}{ref}", element_names, prefix)
            value = _component_value(component)
            lines.append(f"{name} {nodes[0]} {nodes[1]} {value}")
            continue

        # Inferred tier: first-order physics from the component type when no
        # vendor model exists (relay coil, switch contact, lamp filament, …).
        body = infer_subckt_body(component, pin_count)
        if body is not None:
            base = f"INF_{_subckt_name(component, comp_id)[3:]}_{pin_count}P"
            # Same name but different internals (two lamps with different
            # printed values) must not share a definition.
            subckt, suffix = base, 2
            while subckt in inferred and inferred[subckt][1] != body:
                subckt = f"{base}_{suffix}"
                suffix += 1
            inferred[subckt] = (pin_count, body)
            name = _unique(f"X{ref}", element_names, "X")
            lines.append(f"{name} {' '.join(nodes)} {subckt}")
            continue

        # Arity-specific stub names: two occurrences of one part number can
        # surface with different pin counts (a 7-pin booster vs its 4-pin
        # sibling) and SPICE requires instance nodes to match the .subckt.
        subckt = f"{_subckt_name(component, comp_id)}_{pin_count}P"
        subckts[subckt] = pin_count
        name = _unique(f"X{ref}", element_names, "X")
        lines.append(f"{name} {' '.join(nodes)} {subckt}")

    lines.extend(
        _definition_sections(
            bound_models, primitive_wrappers, inferred, subckts, model_cards_for
        )
    )
    lines.append("")
    lines.append(".end")
    return "\n".join(lines) + "\n"


def _definition_sections(
    bound_models: dict[str, str],
    primitive_wrappers: dict[str, tuple[int, str]],
    inferred: dict[str, tuple[int, Any]],
    subckts: dict[str, int],
    model_cards_for: Any,
) -> list[str]:
    """The netlist's definition trailer: vendor models, wrappers, inferred
    bodies, and connectivity stubs (in binding-priority order)."""

    def pin_list(count: int) -> str:
        return " ".join(f"p{i + 1}" for i in range(count))

    lines: list[str] = []
    if bound_models:
        lines.append("")
        lines.append("* vendor models resolved from the SPICE model library")
        lines.extend(bound_models.values())

    if primitive_wrappers:
        lines.append("")
        lines.append("* wrappers binding vendor .model cards to traced pins")
        for wrapper_name, (pin_total, body) in sorted(primitive_wrappers.items()):
            lines.append(f".subckt {wrapper_name} {pin_list(pin_total)}")
            lines.append(body)
            lines.append(".ends")

    if inferred:
        lines.append("")
        lines.append("* INFERRED first-order models (derived from component type,")
        lines.append("* not vendor data) - replace with vendor models when available")
        for subckt, (pin_count, body) in sorted(inferred.items()):
            lines.append(f".subckt {subckt} {pin_list(pin_count)}")
            lines.append(f"* INFERRED: {body.rationale}")
            lines.extend(body.lines)
            lines.append(".ends")
        lines.extend(model_cards_for([body for _, body in inferred.values()]))

    if subckts:
        lines.append("")
        for subckt, pin_count in sorted(subckts.items()):
            lines.append(f".subckt {subckt} {pin_list(pin_count)}")
            lines.append("* stub - substitute the vendor model for simulation")
            # A placeholder element keeps instances alive through simulator
            # elaboration (empty subcircuits are silently optimized away) and
            # makes the netlist runnable as-is for connectivity checks.
            lines.append(f"Rstub p1 p{pin_count} 1G")
            lines.append(".ends")
    return lines


#: Wrapper recipes for vendor ``.model`` device types: terminals expected and
#: the element line instantiating the model inside the generated subckt.
_PRIMITIVE_WRAPPERS: dict[str, tuple[int, str]] = {
    "D": (2, "D1 p1 p2 {name}"),
    "NPN": (3, "Q1 p1 p2 p3 {name}"),
    "PNP": (3, "Q1 p1 p2 p3 {name}"),
    # Bulk tied to source: drawings trace 3 MOSFET terminals.
    "NMOS": (3, "M1 p1 p2 p3 p3 {name}"),
    "PMOS": (3, "M1 p1 p2 p3 p3 {name}"),
    "NJF": (3, "J1 p1 p2 p3 {name}"),
    "PJF": (3, "J1 p1 p2 p3 {name}"),
    "R": (2, "R1 p1 p2 {name}"),
    "C": (2, "C1 p1 p2 {name}"),
    "L": (2, "L1 p1 p2 {name}"),
}


def _primitive_wrapper(model: Any, pin_count: int) -> tuple[str, str] | None:
    """A ``(subckt_name, body)`` wrapper for a vendor ``.model`` card, or None.

    Only binds when the traced pin count matches the device's terminal count —
    anything else would silently mis-wire, so it falls through to inference.
    """
    recipe = _PRIMITIVE_WRAPPERS.get(str(getattr(model, "model_type", "")).upper())
    if recipe is None:
        return None
    terminals, template = recipe
    if pin_count != terminals:
        return None
    wrapper_name = f"MDL_{_sanitize(model.name).upper()}_{terminals}P"
    return wrapper_name, template.format(name=model.name)


def _graph_tenant(graph: dict[str, Any]) -> str | None:
    """Tenant carried on the graph's source — scopes model-library lookups."""
    tenant = (graph.get("source") or {}).get("tenantId")
    return str(tenant) if tenant else None


def _node_assignments(nets: list[dict[str, Any]]) -> dict[str, list[str]]:
    """Component id -> ordered SPICE node names from net memberships."""
    out: dict[str, list[str]] = {}
    used_names: set[str] = set()
    for index, net in enumerate(nets, start=1):
        raw = net.get("name") or net.get("wireId") or f"N{index:03d}"
        node = _unique(_sanitize(str(raw)), used_names, "N")
        for member in net.get("nodes") or []:
            if isinstance(member, dict) and member.get("component"):
                out.setdefault(str(member["component"]), []).append(node)
    return out


def _component_value(component: dict[str, Any]) -> str:
    """Best-effort primitive value (1 when the drawing doesn't print one)."""
    value = str(component.get("value") or "").strip()
    match = re.match(r"^(\d+(?:\.\d+)?)\s*([kKmMuUnNpPfFgG]?)", value)
    if match:
        return match.group(1) + match.group(2).lower()
    return "1"


def _subckt_name(component: dict[str, Any], fallback: str) -> str:
    base = component.get("partNumber") or component.get("type") or fallback
    return "SC_" + _sanitize(str(base)).upper()


def _sanitize(text: str) -> str:
    cleaned = _NODE_SANITIZE_RE.sub("_", text.strip()).strip("_")
    return cleaned or "X"


def _unique(name: str, used: set[str], prefix: str) -> str:
    candidate = name
    counter = 2
    while candidate.upper() in {u.upper() for u in used}:
        candidate = f"{name}_{counter}"
        counter += 1
    used.add(candidate)
    return candidate
