"""Render a Captify schematic graph as EDML for Altair EEvision.

Written to the official "EDML — The Electrical Design Modeling Language"
specification (Altair, version 2025), compiled by EEvision's ``edml2edb``:

* every statement ends with ``;``; objects must be DECLARED before use, so
  all ``Wire`` statements come first, then components with their
  ``Connector`` / ``Cavity`` / ``Join`` blocks,
* identifiers are ``[0-9A-Za-z_]+``; printed names ride in the ``Name``
  property; part numbers and provenance ride as quoted attributes,
* wires classify via ``Type = power|ground|logical`` (MIL-W-5088 ``…N``
  wire ids are grounds), and components display EEvision's built-in
  DIN 40719-2 symbols via ``Imagedsp`` (``R`` resistor, ``K`` relay, …),
* cavities ARE the recovered pin designators, so EEvision shows real pin
  identities at every connection point.

Like the other serializers this is pure and deterministic over the
``captify.schematic.v1`` graph.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from docling_serve.extractors.eevision import (
    cavity_ids_for,
    din_symbol,
    net_label,
    safe_id,
    wire_type,
)


def _q(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def graph_to_edml(graph: dict[str, Any], *, source_name: str) -> str:
    """Serialize a ``captify.schematic.v1`` graph to a spec-conformant EDML string."""
    components = [c for c in graph.get("components") or [] if isinstance(c, dict)]
    nets = [n for n in graph.get("nets") or [] if isinstance(n, dict)]

    lines: list[str] = [
        "// EDML generated by captify-docling-serve schematic extractor",
        f"// Source: {source_name}",
        "",
    ]

    # Root attributes (shown on EEvision's file-select page via Index).
    title = (graph.get("pages") or [{}])[0].get("titleBlock") or {}
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%SZ")
    lines.append(
        "Attributes Index = " + _q("Source\tTitle\tGenerated") + ","
    )
    lines.append(f"    {_q('Source')} = {_q(source_name)},")
    lines.append(f"    {_q('Title')} = {_q(title.get('title') or source_name)},")
    lines.append(f"    {_q('Generated')} = {_q(generated)};")
    lines.append("")

    # 1. Wires — declared before any component can Join them (spec §3.1).
    wire_ref_by_net: dict[str, str] = {}
    lines.append("// Wires (one per traced net)")
    for index, net in enumerate(nets, start=1):
        ref = safe_id(net.get("wireId") or net.get("id"), f"W{index:03d}")
        wire_ref_by_net[str(net.get("id") or index)] = ref
        properties = [f"Name = {_q(net_label(net, index))}"]
        classified = wire_type(net)
        if classified:
            properties.append(f"Type = {classified}")
        if net.get("gauge"):
            properties.append(f'{_q("Gauge")} = {_q(net["gauge"])}')
        if net.get("wireIdSource") == "assigned":
            properties.append(f'{_q("Wire Id Source")} = {_q("assigned")}')
        lines.append(f"Wire {ref} | " + ", ".join(properties) + ";")
    lines.append("")

    # 2. Components: one connector, pin-designator cavities, Joins to wires.
    lines.append("// Components")
    seen_ids: set[str] = set()
    for order, component in enumerate(components, start=1):
        comp_id = safe_id(component.get("id"), f"C{order:04d}")
        if comp_id in seen_ids:
            comp_id = f"{comp_id}_{order}"
        seen_ids.add(comp_id)
        lines.extend(_component_block(comp_id, component, nets, wire_ref_by_net))
        lines.append("")

    return "\n".join(lines) + "\n"


def _component_block(
    comp_id: str,
    component: dict[str, Any],
    nets: list[dict[str, Any]],
    wire_ref_by_net: dict[str, str],
) -> list[str]:
    """The EDML statements for one component (declaration, cavities, joins)."""
    properties = [f"Name = {_q(component.get('refDes') or comp_id)}"]
    symbol = din_symbol(component)
    if symbol:
        properties.append(f"Imagedsp = {_q(f'{symbol},40,40')}")
    for field, label in (
        ("partNumber", "Part No"),
        ("type", "Component Type"),
        ("value", "Value"),
        ("location", "Location"),
    ):
        if component.get(field):
            properties.append(f"{_q(label)} = {_q(component[field])}")
    lines = [f"Component {comp_id} | " + ", ".join(properties) + ";"]

    # Cavities in membership order; the cavity id IS the pin designator.
    raw_id = str(component.get("id"))
    cavity_by_membership = cavity_ids_for(raw_id, nets)
    joins: list[str] = []
    membership = 0
    for net in nets:
        net_ref = wire_ref_by_net.get(str(net.get("id")))
        for node in net.get("nodes") or []:
            if not isinstance(node, dict) or str(node.get("component")) != raw_id:
                continue
            membership += 1
            cavity = cavity_by_membership.get(membership)
            if cavity and net_ref:
                joins.append(f"A.{cavity} -> {net_ref}")
    cavity_ids = [cavity_by_membership[k] for k in sorted(cavity_by_membership)]
    if cavity_ids:
        lines.append("Connector A | Type = invisible;")
        lines.append("Cavity " + ", ".join(cavity_ids) + ";")
    if joins:
        lines.append("Join " + ", ".join(joins) + ";")
    return lines
