"""Render a Captify schematic graph as EDML (Electrical Design Modeling
Language) for Altair EE Vision / Siemens Capital interchange.

EDML is the harness-engineering exchange format the EESV effort targets:
hierarchical ``Component`` declarations with ``Connector``/``Cavity`` pin
detail, ``Join`` statements binding cavities to wires, ``Eyelet`` grounds,
and flat ``Wire`` declarations carrying name/gauge/signal-type. Like
:mod:`netlist`, this module is a pure deterministic serializer over the
``captify.schematic.v1`` graph — no schematic understanding of its own.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

_GROUND_TYPES = ("ground", "eyelet", "stud")


def _q(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _is_ground(component: dict[str, Any]) -> bool:
    ctype = str(component.get("type") or "").lower()
    return any(token in ctype for token in _GROUND_TYPES)


def graph_to_edml(graph: dict[str, Any], *, source_name: str) -> str:
    """Serialize a ``captify.schematic.v1`` graph to an EDML string."""
    components = [c for c in graph.get("components") or [] if isinstance(c, dict)]
    nets = [n for n in graph.get("nets") or [] if isinstance(n, dict)]

    # Wires: one per net, W1.. in net order; named nets keep their printed name.
    wire_ref_by_net_id: dict[str, str] = {}
    for index, net in enumerate(nets, start=1):
        wire_ref_by_net_id[str(net.get("id") or index)] = f"W{index}"

    # Component id -> [(wire ref, pin)] joins, from net membership nodes.
    joins_by_comp: dict[str, list[tuple[str, str | None]]] = {}
    for net in nets:
        wire_ref = wire_ref_by_net_id[str(net.get("id") or "")]
        for node in net.get("nodes") or []:
            if not isinstance(node, dict):
                continue
            comp_id = str(node.get("component") or "")
            if comp_id:
                pin = node.get("pin")
                joins_by_comp.setdefault(comp_id, []).append(
                    (wire_ref, str(pin) if pin is not None else None)
                )

    lines: list[str] = [
        "// ============================================",
        "// EDML - Electrical Design Modeling Language",
        "// Generated by captify-docling-serve schematic extractor",
        f"// Source: {source_name}",
        f"// Date: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S')}Z",
        "// Target: Altair EE Vision / Siemens Capital",
        "// ============================================",
        "",
    ]

    for component in components:
        comp_id = str(component.get("id") or "")
        ref = str(component.get("refDes") or comp_id or "?")
        joins = joins_by_comp.get(comp_id, [])
        if _is_ground(component):
            lines.extend(_eyelet_block(ref, component, joins))
        else:
            lines.extend(_component_block(ref, component, joins))
        lines.append("")

    for net in nets:
        lines.append(_wire_line(wire_ref_by_net_id[str(net.get("id") or "")], net))
    if nets:
        lines.append("")
    lines.append("// End of EDML")
    return "\n".join(lines) + "\n"


def _attributes(component: dict[str, Any]) -> str:
    parts: list[str] = []
    name = component.get("value") or component.get("type")
    if name:
        parts.append(f"Name={_q(name)}")
    if component.get("location"):
        parts.append(f'"Location" = {_q(component.get("location"))}')
    if component.get("partNumber"):
        parts.append(f'"PartNumber" = {_q(component.get("partNumber"))}')
    return ", ".join(parts)


def _component_block(
    ref: str, component: dict[str, Any], joins: list[tuple[str, str | None]]
) -> list[str]:
    attributes = _attributes(component)
    lines = [f"Component {ref}" + (f" | {attributes}" if attributes else "")]
    # Pins become cavities on the component's (single) connector face. The
    # graph's pins are the model's claims; net joins reference them by name.
    pins = [p for p in component.get("pins") or [] if isinstance(p, dict)]
    if pins:
        lines.append('    Connector A | Name="MAIN";')
        for cavity_index, pin in enumerate(pins, start=1):
            pin_name = pin.get("name") or pin.get("number")
            suffix = f" | Name={_q(pin_name)}" if pin_name else ""
            lines.append(f"        Cavity {cavity_index}{suffix};")
    for wire_ref, pin in joins:
        port = f"A.{pin}" if pin else "A"
        lines.append(f"    Join {port} -> {wire_ref};")
    return lines


def _eyelet_block(
    ref: str, component: dict[str, Any], joins: list[tuple[str, str | None]]
) -> list[str]:
    attributes = _attributes(component)
    lines = [f"Eyelet {ref}" + (f" | {attributes}" if attributes else ' | Name="GROUND"')]
    lines.append("    Cavity 1;")
    for wire_ref, _pin in joins:
        lines.append(f"    Join 1 -> {wire_ref};")
    return lines


def _wire_line(wire_ref: str, net: dict[str, Any]) -> str:
    parts: list[str] = []
    name = net.get("name") or net.get("wireId")
    if name:
        parts.append(f"Name={_q(name)}")
    if net.get("gauge"):
        parts.append(f'"Gauge" = {_q(net.get("gauge"))}')
    if net.get("signalType"):
        parts.append(f'"SignalType" = {_q(net.get("signalType"))}')
    return f"Wire {wire_ref}" + (f" | {', '.join(parts)}" if parts else "") + ";"
