"""Static interface for the runtime-compatible legacy Office facade."""

from docling_serve.legacy._implementation import (
    APPROVED_SYSTEM_EXECUTABLE_ROOTS as APPROVED_SYSTEM_EXECUTABLE_ROOTS,
    LEGACY_OFFICE_MIME_TYPES as LEGACY_OFFICE_MIME_TYPES,
    LEGACY_OFFICE_TARGETS as LEGACY_OFFICE_TARGETS,
    LegacyHttpFetchResult as LegacyHttpFetchResult,
    LegacyOfficeCapabilityError as LegacyOfficeCapabilityError,
    LegacyOfficeConversionError as LegacyOfficeConversionError,
    LegacyOfficeConverter as LegacyOfficeConverter,
    LegacyOfficeDoclingConverterManager as LegacyOfficeDoclingConverterManager,
    LegacyOfficeError as LegacyOfficeError,
    LegacyOfficeInputLimitError as LegacyOfficeInputLimitError,
    LegacyOfficeLimitError as LegacyOfficeLimitError,
    LegacyOfficeMissingOutputError as LegacyOfficeMissingOutputError,
    LegacyOfficeOutputLimitError as LegacyOfficeOutputLimitError,
    LegacyOfficeProcessSurvivedError as LegacyOfficeProcessSurvivedError,
    LegacyOfficeScratchLimitError as LegacyOfficeScratchLimitError,
    LegacyOfficeSourceFetchError as LegacyOfficeSourceFetchError,
    LegacyOfficeSourcePolicyError as LegacyOfficeSourcePolicyError,
    LegacyOfficeTimeoutError as LegacyOfficeTimeoutError,
    LegacySourceIdentity as LegacySourceIdentity,
    LibreOfficeHeadlessConverter as LibreOfficeHeadlessConverter,
    PinnedHttpResponse as PinnedHttpResponse,
    PreparedLegacySources as PreparedLegacySources,
    ResolvedGlobalAddress as ResolvedGlobalAddress,
    _build_source_metadata_chunker_class as _build_source_metadata_chunker_class,
    build_converter_manager as build_converter_manager,
    build_legacy_office_public_task_error as build_legacy_office_public_task_error,
    check_legacy_office_capability as check_legacy_office_capability,
    classify_legacy_office_failure as classify_legacy_office_failure,
    fetch_legacy_http_source as fetch_legacy_http_source,
    is_legacy_office_name as is_legacy_office_name,
    original_content_type as original_content_type,
    preconvert_legacy_office_sources as preconvert_legacy_office_sources,
    ray_converter_run_with_retry as ray_converter_run_with_retry,
    terminate_worker_fatally as terminate_worker_fatally,
)
